name: Auto PR from dev to main

on:
  push:
    branches:
      - dev  # Trigger only when there is a push to the 'dev' branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request from dev to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: dev
          base: main
          title: "Auto PR: Merge changes from dev to main"
          body: |
            This pull request was automatically created because of a push to the `dev` branch.
