name: Auto PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history to allow branch comparisons

      - name: Create Pull Request from dev to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: dev
          base: main
          title: "Auto PR: Merge dev into main"
          body: "This PR was created automatically after a push to `dev`."
