name: Create PR from dev to main

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Merge dev into main'
          body: 'Automated PR from dev to main'
          branch: dev
          base: main
