name: Auto PR from dev to main

permissions:
  contents: write
  pull-requests: write


on:
  push:
    branches:
      - dev  # Trigger when there's a push to dev branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to properly compare branches

      - name: Create Pull Request from dev to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token for authentication
          source: dev  # The branch we want to create a PR from
          base: main   # The branch we want to merge into
          title: "Auto PR: Merge dev into main"
          body: |
            This pull request was created automatically after a push to the dev branch.
