name: Auto PR on data.txt Change

on:
  push:
    paths:
      - 'data.txt'  # Trigger only if this file is changed

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create branch
        run: |
          BRANCH="update-data-$(date +%s)"
          git checkout -b $BRANCH
          git add data.txt
          git commit -m "Update data.txt via GitHub Actions" || echo "No changes to commit"
          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated update to data.txt"
          body: "This PR was created automatically when data.txt was updated."
          base: main
