name: Create PR from dev to main

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update PR Title
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_TITLE=$(jq -r '.title' <(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER))

          
          # Remove existing labels from the title
          CLEAN_TITLE=$(echo "$PR_TITLE" | sed -E 's/ \| (stg|rv|bv|im)(,(stg|rv|bv|im))*//g' | sed 's/ *$//')
          
          echo "CLEAN_TITLE: $CLEAN_TITLE"
          
          #gh pr edit ${{ github.event.pull_request.number }} --add-label "QA"
          curl -X POST \
          -H "Authorization: Bearer YOUR_GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/OWNER/REPO/issues/PULL_REQUEST_NUMBER/labels \
          -d '{"labels": ["QA"]}'


          STATUS=$(gh pr view $PR_NUMBER --json state,reviewDecision --jq '.state + " - " + .reviewDecision')

          echo "Current PR Status: $STATUS"

          
          echo "CHANGED_FILES: $CHANGED_FILES"      
